#: import DeviceScreenModel Model.DeviceScreenModel

<DeviceScreenView>
    MDBoxLayout:
        orientation: 'vertical'
        pos_hint: {"top": 1}
        adaptive_height: True
        MDTopAppBar:
            title: "Параметры стимуляции"
            left_action_items: [["arrow-left", lambda x: root.back()]]
        MDGridLayout:
            adaptive_height: True
            cols: 2
            MDLabel:
                id: named
                text: root.name